/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardUploadsRouteImport } from './routes/_authenticated/dashboard.uploads'
import { Route as AuthenticatedDashboardSequenciasRouteImport } from './routes/_authenticated/dashboard.sequencias'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardInteligenciaRouteImport } from './routes/_authenticated/dashboard.inteligencia'
import { Route as AuthenticatedDashboardIntegracoesRouteImport } from './routes/_authenticated/dashboard.integracoes'
import { Route as AuthenticatedDashboardInboxRouteImport } from './routes/_authenticated/dashboard.inbox'
import { Route as AuthenticatedDashboardEventosRouteImport } from './routes/_authenticated/dashboard.eventos'
import { Route as AuthenticatedDashboardCampanhasRouteImport } from './routes/_authenticated/dashboard.campanhas'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardAutomationsRouteImport } from './routes/_authenticated/dashboard.automations'
import { Route as AuthenticatedDashboardAutomacoesRouteImport } from './routes/_authenticated/dashboard.automacoes'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUploadsRoute =
  AuthenticatedDashboardUploadsRouteImport.update({
    id: '/uploads',
    path: '/uploads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSequenciasRoute =
  AuthenticatedDashboardSequenciasRouteImport.update({
    id: '/sequencias',
    path: '/sequencias',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInteligenciaRoute =
  AuthenticatedDashboardInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegracoesRoute =
  AuthenticatedDashboardIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInboxRoute =
  AuthenticatedDashboardInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEventosRoute =
  AuthenticatedDashboardEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCampanhasRoute =
  AuthenticatedDashboardCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAutomationsRoute =
  AuthenticatedDashboardAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAutomacoesRoute =
  AuthenticatedDashboardAutomacoesRouteImport.update({
    id: '/automacoes',
    path: '/automacoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/automacoes': typeof AuthenticatedDashboardAutomacoesRoute
  '/dashboard/automations': typeof AuthenticatedDashboardAutomationsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/dashboard/eventos': typeof AuthenticatedDashboardEventosRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/dashboard/inteligencia': typeof AuthenticatedDashboardInteligenciaRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/sequencias': typeof AuthenticatedDashboardSequenciasRoute
  '/dashboard/uploads': typeof AuthenticatedDashboardUploadsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/automacoes': typeof AuthenticatedDashboardAutomacoesRoute
  '/dashboard/automations': typeof AuthenticatedDashboardAutomationsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/dashboard/eventos': typeof AuthenticatedDashboardEventosRoute
  '/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/dashboard/inteligencia': typeof AuthenticatedDashboardInteligenciaRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/sequencias': typeof AuthenticatedDashboardSequenciasRoute
  '/dashboard/uploads': typeof AuthenticatedDashboardUploadsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/automacoes': typeof AuthenticatedDashboardAutomacoesRoute
  '/_authenticated/dashboard/automations': typeof AuthenticatedDashboardAutomationsRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/campanhas': typeof AuthenticatedDashboardCampanhasRoute
  '/_authenticated/dashboard/eventos': typeof AuthenticatedDashboardEventosRoute
  '/_authenticated/dashboard/inbox': typeof AuthenticatedDashboardInboxRoute
  '/_authenticated/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/_authenticated/dashboard/inteligencia': typeof AuthenticatedDashboardInteligenciaRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/sequencias': typeof AuthenticatedDashboardSequenciasRoute
  '/_authenticated/dashboard/uploads': typeof AuthenticatedDashboardUploadsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/planos'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/automacoes'
    | '/dashboard/automations'
    | '/dashboard/billing'
    | '/dashboard/campanhas'
    | '/dashboard/eventos'
    | '/dashboard/inbox'
    | '/dashboard/integracoes'
    | '/dashboard/inteligencia'
    | '/dashboard/leads'
    | '/dashboard/sequencias'
    | '/dashboard/uploads'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/planos'
    | '/register'
    | '/reset-password'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/automacoes'
    | '/dashboard/automations'
    | '/dashboard/billing'
    | '/dashboard/campanhas'
    | '/dashboard/eventos'
    | '/dashboard/inbox'
    | '/dashboard/integracoes'
    | '/dashboard/inteligencia'
    | '/dashboard/leads'
    | '/dashboard/sequencias'
    | '/dashboard/uploads'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/planos'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/automacoes'
    | '/_authenticated/dashboard/automations'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/campanhas'
    | '/_authenticated/dashboard/eventos'
    | '/_authenticated/dashboard/inbox'
    | '/_authenticated/dashboard/integracoes'
    | '/_authenticated/dashboard/inteligencia'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/sequencias'
    | '/_authenticated/dashboard/uploads'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/uploads': {
      id: '/_authenticated/dashboard/uploads'
      path: '/uploads'
      fullPath: '/dashboard/uploads'
      preLoaderRoute: typeof AuthenticatedDashboardUploadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sequencias': {
      id: '/_authenticated/dashboard/sequencias'
      path: '/sequencias'
      fullPath: '/dashboard/sequencias'
      preLoaderRoute: typeof AuthenticatedDashboardSequenciasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inteligencia': {
      id: '/_authenticated/dashboard/inteligencia'
      path: '/inteligencia'
      fullPath: '/dashboard/inteligencia'
      preLoaderRoute: typeof AuthenticatedDashboardInteligenciaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integracoes': {
      id: '/_authenticated/dashboard/integracoes'
      path: '/integracoes'
      fullPath: '/dashboard/integracoes'
      preLoaderRoute: typeof AuthenticatedDashboardIntegracoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inbox': {
      id: '/_authenticated/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof AuthenticatedDashboardInboxRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/eventos': {
      id: '/_authenticated/dashboard/eventos'
      path: '/eventos'
      fullPath: '/dashboard/eventos'
      preLoaderRoute: typeof AuthenticatedDashboardEventosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/campanhas': {
      id: '/_authenticated/dashboard/campanhas'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof AuthenticatedDashboardCampanhasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/automations': {
      id: '/_authenticated/dashboard/automations'
      path: '/automations'
      fullPath: '/dashboard/automations'
      preLoaderRoute: typeof AuthenticatedDashboardAutomationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/automacoes': {
      id: '/_authenticated/dashboard/automacoes'
      path: '/automacoes'
      fullPath: '/dashboard/automacoes'
      preLoaderRoute: typeof AuthenticatedDashboardAutomacoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardAutomacoesRoute: typeof AuthenticatedDashboardAutomacoesRoute
  AuthenticatedDashboardAutomationsRoute: typeof AuthenticatedDashboardAutomationsRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCampanhasRoute: typeof AuthenticatedDashboardCampanhasRoute
  AuthenticatedDashboardEventosRoute: typeof AuthenticatedDashboardEventosRoute
  AuthenticatedDashboardInboxRoute: typeof AuthenticatedDashboardInboxRoute
  AuthenticatedDashboardIntegracoesRoute: typeof AuthenticatedDashboardIntegracoesRoute
  AuthenticatedDashboardInteligenciaRoute: typeof AuthenticatedDashboardInteligenciaRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardSequenciasRoute: typeof AuthenticatedDashboardSequenciasRoute
  AuthenticatedDashboardUploadsRoute: typeof AuthenticatedDashboardUploadsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardAutomacoesRoute:
      AuthenticatedDashboardAutomacoesRoute,
    AuthenticatedDashboardAutomationsRoute:
      AuthenticatedDashboardAutomationsRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardCampanhasRoute: AuthenticatedDashboardCampanhasRoute,
    AuthenticatedDashboardEventosRoute: AuthenticatedDashboardEventosRoute,
    AuthenticatedDashboardInboxRoute: AuthenticatedDashboardInboxRoute,
    AuthenticatedDashboardIntegracoesRoute:
      AuthenticatedDashboardIntegracoesRoute,
    AuthenticatedDashboardInteligenciaRoute:
      AuthenticatedDashboardInteligenciaRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardSequenciasRoute:
      AuthenticatedDashboardSequenciasRoute,
    AuthenticatedDashboardUploadsRoute: AuthenticatedDashboardUploadsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
