GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.audit_logs,
  public.automacoes,
  public.campanhas,
  public.client_strategy_profiles,
  public.empresas,
  public.eventos_uploads,
  public.financeiro,
  public.icp_profiles,
  public.integrations,
  public.invoices,
  public.leads,
  public.leads_eventos,
  public.meeting_feedback,
  public.outreach_logs,
  public.planos,
  public.platform_settings,
  public.profiles,
  public.sequencias,
  public.subscriptions,
  public.tenants,
  public.user_roles,
  public.workflow_runs,
  public.workflows
TO authenticated;

GRANT ALL ON TABLE
  public.audit_logs,
  public.automacoes,
  public.campanhas,
  public.client_strategy_profiles,
  public.empresas,
  public.eventos_uploads,
  public.financeiro,
  public.icp_profiles,
  public.integrations,
  public.invoices,
  public.leads,
  public.leads_eventos,
  public.meeting_feedback,
  public.outreach_logs,
  public.planos,
  public.platform_settings,
  public.profiles,
  public.sequencias,
  public.subscriptions,
  public.tenants,
  public.user_roles,
  public.workflow_runs,
  public.workflows
TO service_role;